### PR TITLE
IP408 support

### PR DESCRIPTION
**Pull request by keenanlang**
Support from Kurt Goetze for Acromag IP408

### CODE REVIEW

**Comment by MarkRivers** [comment]
This looks fine to me.  Has it been tested in real-life?

**Comment by keenanlang** [comment]
Kurt says he has tested it in his office, but I don't know to what extent. I installed it today at Sector 6 where they will be trying it out over the next week.

**Comment by MarkRivers** [comment]
Sounds good.

**Comment by keenanlang** [comment]
Received confirmation from Doug Robinson that the support has been tested and everything looks good.

**Pull request merged**
